import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import CountdownTimer from "../component";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <a href="https://www.instagram.com/icetea.media/?hl=en">
            PICASSOCIAL!
          </a>
        </h1>
        <div style={{ display: "flex", justifyContent: "center" }}>
          <p style={{ fontSize: "3vw", lineHeight: "3.5vw", width: "16vw" }}>
            Open In{" "}
          </p>
          <CountdownTimer targetDate="08-15-2023" />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
